# Generated by Django 6.0.6 on 2026-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
