# Generated by Django 6.0.6 on 2026-07-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_gateway_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='gateway_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='refund',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
