# Generated by Django 6.0.6 on 2026-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_refund_gateway_refund_id_refund_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='includes_all_paid_courses',
            field=models.BooleanField(default=False, help_text='Access every paid course without buying them individually.'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='includes_certificates',
            field=models.BooleanField(default=False, help_text='Earn completion certificates.'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='includes_live_sessions',
            field=models.BooleanField(default=False, help_text='Join live classes and cohorts.'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='priority_support',
            field=models.BooleanField(default=False, help_text='Support promise only — nothing in the API is gated on it.'),
        ),
    ]
