# Generated by Django 6.0.6 on 2026-09-02 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_intro_video_key_course_thumbnail_key'),
        ('payments', '0004_pricingplan_includes_all_paid_courses_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('share_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Earned'), ('reversed', 'Reversed (refunded)')], default='pending', max_length=20)),
                ('earned_at', models.DateTimeField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_earnings', to='courses.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_earnings', to='payments.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_earning', to='payments.orderitem')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='payments.trainerpayout')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at', '-id'],
                'indexes': [models.Index(fields=['trainer', '-earned_at'], name='payments_tr_trainer_d749b5_idx'), models.Index(fields=['trainer', 'status', 'payout'], name='payments_tr_trainer_4a3449_idx')],
            },
        ),
    ]
