# Generated by Django 6.0.6 on 2026-08-13 06:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(default='Jigyasa', max_length=120)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('default_currency', models.CharField(default='INR', help_text='Currency for new orders and billing totals. Does NOT convert existing prices — change your course prices and plans too.', max_length=8, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Use a 3-letter uppercase ISO code, e.g. INR.')])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Applied to the discounted subtotal at checkout. Orders already placed keep the rate they were quoted at.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Stored for trainer revenue share. NOTHING COMPUTES PAYOUTS YET — changing this does not move money.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('razorpay_key_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=255)),
                ('razorpay_webhook_secret', models.CharField(blank=True, max_length=255)),
                ('course_approval_required', models.BooleanField(default=True, help_text="Off: a trainer's submission publishes immediately, no review.")),
                ('trainer_self_onboarding', models.BooleanField(default=True, help_text='Off: nobody can register as a trainer; an admin creates them.')),
                ('allow_coupon_codes', models.BooleanField(default=True, help_text='Off: coupon codes are rejected at checkout.')),
                ('smart_classroom_module', models.BooleanField(default=False, help_text='Not enforced — the module does not exist yet.')),
                ('ai_suggestions', models.BooleanField(default=False, help_text='Not enforced — the feature does not exist yet.')),
                ('container_classrooms', models.BooleanField(default=False, help_text='Not enforced — Phase 2.')),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
