# Generated by Django 6.0.6 on 2026-09-01 08:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_platform_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsetting',
            name='platform_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text="The platform's default cut. Trainers keep (100 − this) unless a rate is set on their own profile, which overrides it. NOTHING COMPUTES PAYOUTS YET — changing this does not move money.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
