# Generated by Django 5.2.17 on 2026-09-27 17:17

import accounts.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_cover_color_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_account_number',
            field=accounts.crypto.PayoutEncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_ifsc',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
