# Generated by Django 6.0.6 on 2026-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_tags_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
