# Generated by Django 6.0.6 on 2026-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trainerprofile_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='revenue_share_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="This trainer's cut, as a percentage. Leave blank to follow the platform default (100 − platform commission). Set it only to record a deal negotiated with this trainer specifically.", max_digits=5, null=True),
        ),
    ]
