# Generated by Django 6.0.6 on 2026-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_inherit_platform_revenue_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='revenue_share_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank so this trainer follows the platform commission — changing it platform-wide then moves them too. Set a number only to record a rate negotiated with this trainer specifically, which pins them and opts them out of platform-wide changes.', max_digits=5, null=True),
        ),
    ]
