# Generated by Django 6.0.6 on 2026-09-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_trainerprofile_revenue_share_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
