# Generated by Django 6.0.6 on 2026-09-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_trainerprofile_review_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_account_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_account_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_account_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='payout_bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
