# Generated by Django 6.0.6 on 2026-09-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_trainerprofile_payout_account_holder_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_platformsetting_platform_commission_percent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'last_login'], name='user_active_seen_idx'),
        ),
    ]
