# Generated by Django 6.0.6 on 2026-07-30 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0004_lesson_video_key'),
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['activity'],
            },
        ),
        migrations.AddField(
            model_name='discussionreply',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='courses.tag'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='visibility',
            field=models.CharField(choices=[('community', 'My community'), ('public', 'Public')], default='community', max_length=20),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='engagement__content_f1bc63_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_vote_per_user_per_post')],
            },
        ),
    ]
