# Generated by Django 6.0.6 on 2026-07-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='individualbooking',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
