# Generated by Django 5.2.17 on 2026-09-11 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiondoubt',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessiondoubt',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessiondoubt',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_doubts', to=settings.AUTH_USER_MODEL),
        ),
    ]
