# Generated by Django 6.0.6 on 2026-07-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_individualbooking_notes_individualbooking_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
