# Generated by Django 6.0.6 on 2026-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
