# Generated by Django 6.0.6 on 2026-08-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_video_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('free', 'Free'), ('bulk', 'Bulk (institution)'), ('institution', 'Institution'), ('subscription', 'Subscription')], default='free', max_length=20),
        ),
    ]
