# Generated by Django 6.0.6 on 2026-08-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_enrollment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='has_unapproved_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
