# Generated by Django 6.0.6 on 2026-08-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_certificate_enabled_course_completion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
