"""
Django settings for Jigayasa project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file (kept out of source control).
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    CORS_ALLOWED_ORIGINS=(list, ["http://localhost:3000", "http://127.0.0.1:3000"]),
    JWT_ACCESS_MINUTES=(int, 60),
    JWT_REFRESH_DAYS=(int, 7),
)
environ.Env.read_env(BASE_DIR / ".env")


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_spectacular',
]

LOCAL_APPS = [
    'core',
    'accounts',
    'courses',
    'payments',
    'live',
    'recordings',
    'library',
    'assessments',
    'certificates',
    'engagement',
    'notifications',
    'classrooms',
    'analytics',
    'social',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Jigaysa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Jigaysa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": env("DB_ENGINE", default="django.db.backends.mysql"),
        "NAME": env("DB_NAME", default="jigaysa"),
        "USER": env("DB_USER", default="root"),
        "PASSWORD": env("DB_PASSWORD", default=""),
        "HOST": env("DB_HOST", default="127.0.0.1"),
        "PORT": env("DB_PORT", default="3306"),
    }
}

# MySQL-specific tuning: force InnoDB + utf8mb4 so unique varchar indexes
# (email, slug) don't hit MyISAM's 1000-byte key limit. Applied only for the
# MySQL backend, keeping the config drop-in ready for PostgreSQL.
if "mysql" in DATABASES["default"]["ENGINE"]:
    DATABASES["default"]["OPTIONS"] = {
        "charset": "utf8mb4",
        "init_command": "SET default_storage_engine=INNODB",
    }


# Custom user model (must be set before the first migration).
AUTH_USER_MODEL = "accounts.User"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "core.schema.RoleAwareAutoSchema",
    "DEFAULT_PAGINATION_CLASS": "core.pagination.DefaultPagination",
    "PAGE_SIZE": 20,
}

# SimpleJWT — access lifetime covers §3.1 "session timeout";
# rotation + blacklist covers multi-device logout.
SIMPLE_JWT = {
    # This platform authenticates only by JWT, so nothing else would ever write
    # ``last_login`` — leaving it null on every account for ever and making any
    # "active users" metric read zero regardless of real traffic. One
    # single-row UPDATE per login, next to the LoginActivity INSERT we already
    # do on the same path.
    "UPDATE_LAST_LOGIN": True,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env("JWT_ACCESS_MINUTES")),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env("JWT_REFRESH_DAYS")),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# OpenAPI schema (drf-spectacular)
SPECTACULAR_SETTINGS = {
    "TITLE": "Jigaysa Smart Hybrid LMS API",
    "DESCRIPTION": (
        "API for the Smart Hybrid LMS platform.\n\n"
        "**Student modules live:** Auth (incl. OTP + password reset), Courses & "
        "enrollment, Free Library, Live Classes, Assessments, Discussions & "
        "Community, Notifications, Payments, File Uploads.\n\n"
        "> 💳 **Payments run on Razorpay.** Checkout flow: `POST /orders/` → "
        "`POST /orders/{id}/checkout/` (returns Razorpay order params) → open "
        "Razorpay Checkout in the browser → `POST /orders/{id}/verify/` with the "
        "handler payload. The `payment.captured` webhook at "
        "`POST /payments/webhook/razorpay/` is the authoritative confirmation and "
        "fulfils the order even if the browser is closed mid-payment. "
        "`POST /orders/{id}/pay/` is a **mock** confirmation that only works when "
        "no Razorpay keys are configured (dev/test).\n\n"
        "> Also pending: refunds, EMI/installments, pay-per-session checkout, "
        "corporate/group pricing, referral credits. Recordings (§3.11) and "
        "Smart Classroom (§3.7–3.8) are not exposed yet."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# CORS — origins for the web/mobile frontend.
# Explicit origins come from the environment (defaults to localhost:3000).
CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS")

# Wildcard subdomains can't be expressed as plain origins, so match any
# *.jigyaasaa.com host (http/https) via regex.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://([\w-]+\.)*jigyaasaa\.com$",
]

# Public URL of the student web app. Used for Razorpay checkout branding and
# the post-payment redirect; also the origin the browser calls this API from.
FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:3000")

# --- Razorpay (PRD §3.13) ---------------------------------------------------
# Leave RAZORPAY_KEY_ID empty to disable the gateway; checkout then falls back
# to the mock confirmation in payments.services.pay_order (dev/test only).
# RAZORPAY_WEBHOOK_SECRET is set when creating the webhook in the Razorpay
# dashboard and is intentionally different from the API secret.
RAZORPAY_KEY_ID = env("RAZORPAY_KEY_ID", default="")
RAZORPAY_KEY_SECRET = env("RAZORPAY_KEY_SECRET", default="")
RAZORPAY_WEBHOOK_SECRET = env("RAZORPAY_WEBHOOK_SECRET", default="")
# Company name / logo shown inside the Razorpay Checkout modal.
RAZORPAY_CHECKOUT_NAME = env("RAZORPAY_CHECKOUT_NAME", default="Jigyaasaa")
RAZORPAY_CHECKOUT_LOGO = env("RAZORPAY_CHECKOUT_LOGO", default="")

# Pluggable SMS/OTP provider (mock console provider in dev).
SMS_PROVIDER = env("SMS_PROVIDER", default="accounts.providers.ConsoleSMSProvider")

# --- Object storage (S3 / S3-compatible) for media, thumbnails & videos ----
# Direct-to-S3 uploads: the API hands the frontend a short-lived *private*
# presigned PUT URL (see core.storage / the /api/v1/uploads/ endpoints); the
# browser uploads straight to the bucket and stores the returned object key in
# the DB. Leave the bucket empty to disable the upload endpoints (they return
# 503). ``AWS_S3_ENDPOINT_URL`` targets S3-compatible providers (Cloudflare R2,
# MinIO, DigitalOcean Spaces); leave blank for AWS S3.
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID", default="")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY", default="")
AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME", default="")
AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="ap-south-1")
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL", default="")
AWS_S3_CUSTOM_DOMAIN = env("AWS_S3_CUSTOM_DOMAIN", default="")  # CDN host, no scheme
AWS_S3_ADDRESSING_STYLE = env("AWS_S3_ADDRESSING_STYLE", default="virtual")
AWS_S3_UPLOAD_EXPIRY = env.int("AWS_S3_UPLOAD_EXPIRY", default=900)  # 15 min
AWS_S3_DOWNLOAD_EXPIRY = env.int("AWS_S3_DOWNLOAD_EXPIRY", default=3600)  # 1 hr
# Hard cap advertised to clients (enforced via presigned-POST policy).
AWS_S3_MAX_UPLOAD_BYTES = env.int(
    "AWS_S3_MAX_UPLOAD_BYTES", default=1024 * 1024 * 1024  # 1 GiB
)


# --- Social publishing (PRD §3.3 course promotion) --------------------------
# OAuth client credentials for the networks a trainer can connect from the
# panel. Leave a pair blank to disable that network: its card renders "not
# configured" and the connect endpoint returns 503 rather than failing mid-flow.
#
# These are per-deployment infrastructure, not tunable settings — the redirect
# URI registered in each platform's console is tied to this deployment's domain,
# so the credentials belong beside it in the environment.
LINKEDIN_CLIENT_ID = env("LINKEDIN_CLIENT_ID", default="")
LINKEDIN_CLIENT_SECRET = env("LINKEDIN_CLIENT_SECRET", default="")

# Facebook and Instagram are one Meta app: a single authorization returns every
# Page the trainer admins plus each Page's linked Instagram Business account.
META_APP_ID = env("META_APP_ID", default="")
META_APP_SECRET = env("META_APP_SECRET", default="")
META_GRAPH_VERSION = env("META_GRAPH_VERSION", default="v21.0")

# Public base URL the networks redirect back to, e.g. https://api.example.com.
# Must match the redirect URI registered in each platform's console exactly.
# Blank falls back to the incoming request's host, which is fine in dev and
# wrong behind a proxy.
SOCIAL_OAUTH_REDIRECT_BASE = env("SOCIAL_OAUTH_REDIRECT_BASE", default="")

# Fernet key encrypting the stored OAuth tokens (social.crypto). Generate with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Never store this in the database it protects. Rotating it makes every stored
# token undecryptable and forces every trainer to reconnect.
SOCIAL_TOKEN_KEY = env("SOCIAL_TOKEN_KEY", default="")

# LinkedIn versions its REST API by month and rejects a call without the header.
# Pinned rather than tracking "latest" so their release schedule cannot break
# publishing on a random morning; move it forward deliberately, roughly yearly.
LINKEDIN_API_VERSION = env("LINKEDIN_API_VERSION", default="202405")

# Where a promoted post sends people. Joined to the *origin* of FRONTEND_URL,
# not to FRONTEND_URL itself, which carries the student app's own path segment
# (see social.oauth.frontend_origin). Configurable because the public catalog
# route is a frontend decision and a wrong guess here 404s every click on every
# post we publish.
SOCIAL_COURSE_URL_PATH = env("SOCIAL_COURSE_URL_PATH", default="/courses/{slug}")

# How long a trainer's earning must age before a payout can sweep it up. Covers
# the window in which a refund is likely, so a reversal lands on money that has
# not left yet. A business decision, not a constant — see payments.earnings.
TRAINER_PAYOUT_HOLD_DAYS = env.int("TRAINER_PAYOUT_HOLD_DAYS", default=7)


# --- Live sessions: Jitsi (PRD §3.5) ----------------------------------------
# Live classes run on a dedicated Jitsi instance at meet.jigaysa.com. Django
# never touches media; it signs a short-lived JWT naming the room and the
# caller's powers (see live.meeting).
#
# Leave JITSI_APP_SECRET empty to disable the integration: ``join`` then returns
# the stored ``join_url`` exactly as before, the same way an empty
# RAZORPAY_KEY_ID disables the payment gateway. That makes this safe to deploy
# before the secret is in place.
#
# The secret must byte-match ``app_secret`` in the bridge's Prosody vhost. If
# the two drift, every join fails with an opaque auth error and neither side's
# logs say anything useful — check it first when debugging.
JITSI_DOMAIN = env("JITSI_DOMAIN", default="")
JITSI_APP_ID = env("JITSI_APP_ID", default="jigyasa")
JITSI_APP_SECRET = env("JITSI_APP_SECRET", default="")
# A join URL is a bearer credential, so it must not outlive the class it opens.
JITSI_TOKEN_TTL_MINUTES = env.int("JITSI_TOKEN_TTL_MINUTES", default=240)


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Datetimes are always *stored* in UTC (USE_TZ). TIME_ZONE only sets the default
# display zone: API responses render as +05:30 and naive datetimes are read as
# IST. Per-user overrides live on ``accounts.Profile.timezone``.
TIME_ZONE = env("TIME_ZONE", default="Asia/Kolkata")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Destination for `collectstatic` in production (served by nginx/whitenoise).
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
