# Generated by Django 6.0.6 on 2026-08-27 05:39

import django.db.models.deletion
import social.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('access_token', social.crypto.EncryptedTextField(blank=True, default='')),
                ('refresh_token', social.crypto.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('expired', 'Token expired'), ('revoked', 'Revoked upstream')], default='connected', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('provider_meta', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'display_name'],
                'indexes': [models.Index(fields=['user', 'provider'], name='social_soci_user_id_585cb6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'provider_account_id'), name='uniq_social_account_per_destination')],
            },
        ),
    ]
