# Generated by Django 5.2.17 on 2026-09-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image_source',
            field=models.CharField(choices=[('thumbnail', 'Course thumbnail'), ('promo_card', 'Auto promo card'), ('custom', 'Uploaded image'), ('none', 'No image')], default='thumbnail', max_length=20),
        ),
    ]
