# Generated by Django 6.0.6 on 2026-09-01 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_intro_video_key_course_thumbnail_key'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(choices=[('launch', 'Just launched'), ('discount', 'Limited discount'), ('last_seats', 'Last seats'), ('testimonial', 'Learner testimonial'), ('milestone', 'Milestone')], max_length=32)),
                ('caption', models.TextField()),
                ('hashtags', models.CharField(blank=True, max_length=255)),
                ('image_source', models.CharField(choices=[('thumbnail', 'Course thumbnail'), ('promo_card', 'Auto promo card'), ('none', 'No image')], default='thumbnail', max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('link_url', models.URLField(blank=True, max_length=1024)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('partial', 'Partly published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_campaigns', to='courses.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('x', 'X'), ('youtube', 'YouTube')], max_length=20)),
                ('account_label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('published_caption', models.TextField(blank=True)),
                ('provider_post_id', models.CharField(blank=True, max_length=255)),
                ('permalink', models.URLField(blank=True, max_length=1024)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_posts', to='social.socialaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.campaign')),
            ],
            options={
                'ordering': ['provider', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['trainer', '-created_at'], name='social_camp_trainer_be81e4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_for'], name='social_camp_status_7f06e3_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpost',
            index=models.Index(fields=['status', 'campaign'], name='social_camp_status_9c53fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignpost',
            constraint=models.UniqueConstraint(fields=('campaign', 'account'), name='uniq_campaign_post_per_account'),
        ),
    ]
